# parameters.yaml

# Parameters file format version 0.1
# This is a draft YAML file for data in a single experiment run
# Subject to changes as needed

paths:
    base: <To be set to the local computer's data directory>
    protocol: HB_139_DAMGO/
    unit: 825_12h24m37s/20200825_12h24m37s_units_ts.mat
    treatments: 825_12h24m37s/20200825_12h24m37s_treatments.csv
    executables: ...

experiment_metadata:
    experiment_name: 825_12h24m37s
    experiment_description: Apply DAMGO and other treatments
    experiment_date: 2020-08-25
    researchers: Elayne Vieira Dias, Elyssa Margolis
    
data_cleaning:
   activity_threshold: .5

spike_sorting:
   method: matlab custom
 
models:
   firing_rate_model:
        model_type: ...
   dose_response_model:
        model_type: sigmoid
        priors: ...
        inits: ...
